[package]
name = "binlang"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
string-interner = "0.19.0"
string_cache = "0.8.9"
topological-sort = "0.2.2"
